apiVersion: v2
name: ghost-blog
description: A Helm chart for Ghost blogging platform
version: 0.1.0
appVersion: "5.75.1"
dependencies:
  - name: mysql
    version: 9.10.5
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
