ghost:
  image:
    repository: ghost
    tag: "5.75.1-alpine"
    pullPolicy: IfNotPresent

  settings:
    url: http://ghost.local
    admin:
      url: http://ghost.local/ghost

replicaCount: 1

service:
  type: ClusterIP
  port: 2368

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ghost.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ghost-tls
      hosts:
        - ghost.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

backup:
  velero:
    enabled: true
    annotations:
      velero.io/backup-volumes: data,backup
      backup.velero.io/backup-volumes-excludes: temp-data

mysql:
  enabled: true
  auth:
    rootPassword: rootpassword
    database: ghost
    username: ghost
    password: ghostpassword
  primary:
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    persistence:
      enabled: true
      size: 8Gi
    backup:
      enabled: true
      cronjob:
        schedule: "0 2 * * *"  # Бэкап каждый день в 2 утра
      persistence:
        enabled: true
        storageClass: "standard"  # Укажите ваш storage class
        size: 8Gi
