{{- if .Values.mysql.primary.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ghost-blog.fullname" . }}-backup
spec:
  schedule: {{ .Values.mysql.primary.backup.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mysql:8.0
            env:
            - name: MYSQL_HOST
              value: {{ .Release.Name }}-mysql
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database }}
            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /backup
              mysqldump --host=$MYSQL_HOST --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE > /backup/backup-$(date +%Y%m%d-%H%M%S).sql
              gzip /backup/*.sql
            volumeMounts:
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: {{ include "ghost-blog.fullname" . }}-backup
{{- end }}
